@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/65315a6588c749b864a0345d
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/65315c8488c749b864a0346d
Content-Type: application/json
Accept: application/json
withCredentials: true